// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: heartbeat.proto

package licensepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	TokenPem      []byte                 `protobuf:"bytes,2,opt,name=token_pem,json=tokenPem,proto3" json:"token_pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_heartbeat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_heartbeat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_heartbeat_proto_rawDescGZIP(), []int{0}
}

func (x *SyncRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SyncRequest) GetTokenPem() []byte {
	if x != nil {
		return x.TokenPem
	}
	return nil
}

type SyncResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TokenPem       []byte                 `protobuf:"bytes,1,opt,name=token_pem,json=tokenPem,proto3" json:"token_pem,omitempty"`
	ServerTimeUnix int64                  `protobuf:"varint,2,opt,name=server_time_unix,json=serverTimeUnix,proto3" json:"server_time_unix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_heartbeat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_heartbeat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_heartbeat_proto_rawDescGZIP(), []int{1}
}

func (x *SyncResponse) GetTokenPem() []byte {
	if x != nil {
		return x.TokenPem
	}
	return nil
}

func (x *SyncResponse) GetServerTimeUnix() int64 {
	if x != nil {
		return x.ServerTimeUnix
	}
	return 0
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_heartbeat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_heartbeat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_heartbeat_proto_rawDescGZIP(), []int{2}
}

type PingResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServerTimeUnix   int64                  `protobuf:"varint,1,opt,name=server_time_unix,json=serverTimeUnix,proto3" json:"server_time_unix,omitempty"`
	TokenExpiresUnix int64                  `protobuf:"varint,2,opt,name=token_expires_unix,json=tokenExpiresUnix,proto3" json:"token_expires_unix,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_heartbeat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_heartbeat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_heartbeat_proto_rawDescGZIP(), []int{3}
}

func (x *PingResponse) GetServerTimeUnix() int64 {
	if x != nil {
		return x.ServerTimeUnix
	}
	return 0
}

func (x *PingResponse) GetTokenExpiresUnix() int64 {
	if x != nil {
		return x.TokenExpiresUnix
	}
	return 0
}

var File_heartbeat_proto protoreflect.FileDescriptor

const file_heartbeat_proto_rawDesc = "" +
	"\n" +
	"\x0fheartbeat.proto\x12\fheartbeat.v1\"C\n" +
	"\vSyncRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\ttoken_pem\x18\x02 \x01(\fR\btokenPem\"U\n" +
	"\fSyncResponse\x12\x1b\n" +
	"\ttoken_pem\x18\x01 \x01(\fR\btokenPem\x12(\n" +
	"\x10server_time_unix\x18\x02 \x01(\x03R\x0eserverTimeUnix\"\r\n" +
	"\vPingRequest\"f\n" +
	"\fPingResponse\x12(\n" +
	"\x10server_time_unix\x18\x01 \x01(\x03R\x0eserverTimeUnix\x12,\n" +
	"\x12token_expires_unix\x18\x02 \x01(\x03R\x10tokenExpiresUnix2\x90\x01\n" +
	"\x10HeartbeatService\x12=\n" +
	"\x04Sync\x12\x19.heartbeat.v1.SyncRequest\x1a\x1a.heartbeat.v1.SyncResponse\x12=\n" +
	"\x04Ping\x12\x19.heartbeat.v1.PingRequest\x1a\x1a.heartbeat.v1.PingResponseB1Z/github.com/go-ragnaros/go-pulse/proto/licensepbb\x06proto3"

var (
	file_heartbeat_proto_rawDescOnce sync.Once
	file_heartbeat_proto_rawDescData []byte
)

func file_heartbeat_proto_rawDescGZIP() []byte {
	file_heartbeat_proto_rawDescOnce.Do(func() {
		file_heartbeat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_heartbeat_proto_rawDesc), len(file_heartbeat_proto_rawDesc)))
	})
	return file_heartbeat_proto_rawDescData
}

var file_heartbeat_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_heartbeat_proto_goTypes = []any{
	(*SyncRequest)(nil),  // 0: heartbeat.v1.SyncRequest
	(*SyncResponse)(nil), // 1: heartbeat.v1.SyncResponse
	(*PingRequest)(nil),  // 2: heartbeat.v1.PingRequest
	(*PingResponse)(nil), // 3: heartbeat.v1.PingResponse
}
var file_heartbeat_proto_depIdxs = []int32{
	0, // 0: heartbeat.v1.HeartbeatService.Sync:input_type -> heartbeat.v1.SyncRequest
	2, // 1: heartbeat.v1.HeartbeatService.Ping:input_type -> heartbeat.v1.PingRequest
	1, // 2: heartbeat.v1.HeartbeatService.Sync:output_type -> heartbeat.v1.SyncResponse
	3, // 3: heartbeat.v1.HeartbeatService.Ping:output_type -> heartbeat.v1.PingResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_heartbeat_proto_init() }
func file_heartbeat_proto_init() {
	if File_heartbeat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_heartbeat_proto_rawDesc), len(file_heartbeat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_heartbeat_proto_goTypes,
		DependencyIndexes: file_heartbeat_proto_depIdxs,
		MessageInfos:      file_heartbeat_proto_msgTypes,
	}.Build()
	File_heartbeat_proto = out.File
	file_heartbeat_proto_goTypes = nil
	file_heartbeat_proto_depIdxs = nil
}
