// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: heartbeat.proto

package licensepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RenewRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MachineFingerprint string                 `protobuf:"bytes,1,opt,name=machine_fingerprint,json=machineFingerprint,proto3" json:"machine_fingerprint,omitempty"`
	CurrentCertPem     []byte                 `protobuf:"bytes,2,opt,name=current_cert_pem,json=currentCertPem,proto3" json:"current_cert_pem,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RenewRequest) Reset() {
	*x = RenewRequest{}
	mi := &file_heartbeat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewRequest) ProtoMessage() {}

func (x *RenewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_heartbeat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewRequest.ProtoReflect.Descriptor instead.
func (*RenewRequest) Descriptor() ([]byte, []int) {
	return file_heartbeat_proto_rawDescGZIP(), []int{0}
}

func (x *RenewRequest) GetMachineFingerprint() string {
	if x != nil {
		return x.MachineFingerprint
	}
	return ""
}

func (x *RenewRequest) GetCurrentCertPem() []byte {
	if x != nil {
		return x.CurrentCertPem
	}
	return nil
}

type RenewResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NewCertPem     []byte                 `protobuf:"bytes,1,opt,name=new_cert_pem,json=newCertPem,proto3" json:"new_cert_pem,omitempty"`
	ServerTimeUnix int64                  `protobuf:"varint,2,opt,name=server_time_unix,json=serverTimeUnix,proto3" json:"server_time_unix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RenewResponse) Reset() {
	*x = RenewResponse{}
	mi := &file_heartbeat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewResponse) ProtoMessage() {}

func (x *RenewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_heartbeat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewResponse.ProtoReflect.Descriptor instead.
func (*RenewResponse) Descriptor() ([]byte, []int) {
	return file_heartbeat_proto_rawDescGZIP(), []int{1}
}

func (x *RenewResponse) GetNewCertPem() []byte {
	if x != nil {
		return x.NewCertPem
	}
	return nil
}

func (x *RenewResponse) GetServerTimeUnix() int64 {
	if x != nil {
		return x.ServerTimeUnix
	}
	return 0
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_heartbeat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_heartbeat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_heartbeat_proto_rawDescGZIP(), []int{2}
}

type PingResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ServerTimeUnix      int64                  `protobuf:"varint,1,opt,name=server_time_unix,json=serverTimeUnix,proto3" json:"server_time_unix,omitempty"`
	RootCertExpiresUnix int64                  `protobuf:"varint,2,opt,name=root_cert_expires_unix,json=rootCertExpiresUnix,proto3" json:"root_cert_expires_unix,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_heartbeat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_heartbeat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_heartbeat_proto_rawDescGZIP(), []int{3}
}

func (x *PingResponse) GetServerTimeUnix() int64 {
	if x != nil {
		return x.ServerTimeUnix
	}
	return 0
}

func (x *PingResponse) GetRootCertExpiresUnix() int64 {
	if x != nil {
		return x.RootCertExpiresUnix
	}
	return 0
}

var File_heartbeat_proto protoreflect.FileDescriptor

const file_heartbeat_proto_rawDesc = "" +
	"\n" +
	"\x0fheartbeat.proto\x12\n" +
	"license.v1\"i\n" +
	"\fRenewRequest\x12/\n" +
	"\x13machine_fingerprint\x18\x01 \x01(\tR\x12machineFingerprint\x12(\n" +
	"\x10current_cert_pem\x18\x02 \x01(\fR\x0ecurrentCertPem\"[\n" +
	"\rRenewResponse\x12 \n" +
	"\fnew_cert_pem\x18\x01 \x01(\fR\n" +
	"newCertPem\x12(\n" +
	"\x10server_time_unix\x18\x02 \x01(\x03R\x0eserverTimeUnix\"\r\n" +
	"\vPingRequest\"m\n" +
	"\fPingResponse\x12(\n" +
	"\x10server_time_unix\x18\x01 \x01(\x03R\x0eserverTimeUnix\x123\n" +
	"\x16root_cert_expires_unix\x18\x02 \x01(\x03R\x13rootCertExpiresUnix2\x93\x01\n" +
	"\x0eLicenseService\x12F\n" +
	"\x0fRenewClientCert\x12\x18.license.v1.RenewRequest\x1a\x19.license.v1.RenewResponse\x129\n" +
	"\x04Ping\x12\x17.license.v1.PingRequest\x1a\x18.license.v1.PingResponseB1Z/github.com/go-ragnaros/go-pulse/proto/licensepbb\x06proto3"

var (
	file_heartbeat_proto_rawDescOnce sync.Once
	file_heartbeat_proto_rawDescData []byte
)

func file_heartbeat_proto_rawDescGZIP() []byte {
	file_heartbeat_proto_rawDescOnce.Do(func() {
		file_heartbeat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_heartbeat_proto_rawDesc), len(file_heartbeat_proto_rawDesc)))
	})
	return file_heartbeat_proto_rawDescData
}

var file_heartbeat_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_heartbeat_proto_goTypes = []any{
	(*RenewRequest)(nil),  // 0: license.v1.RenewRequest
	(*RenewResponse)(nil), // 1: license.v1.RenewResponse
	(*PingRequest)(nil),   // 2: license.v1.PingRequest
	(*PingResponse)(nil),  // 3: license.v1.PingResponse
}
var file_heartbeat_proto_depIdxs = []int32{
	0, // 0: license.v1.LicenseService.RenewClientCert:input_type -> license.v1.RenewRequest
	2, // 1: license.v1.LicenseService.Ping:input_type -> license.v1.PingRequest
	1, // 2: license.v1.LicenseService.RenewClientCert:output_type -> license.v1.RenewResponse
	3, // 3: license.v1.LicenseService.Ping:output_type -> license.v1.PingResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_heartbeat_proto_init() }
func file_heartbeat_proto_init() {
	if File_heartbeat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_heartbeat_proto_rawDesc), len(file_heartbeat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_heartbeat_proto_goTypes,
		DependencyIndexes: file_heartbeat_proto_depIdxs,
		MessageInfos:      file_heartbeat_proto_msgTypes,
	}.Build()
	File_heartbeat_proto = out.File
	file_heartbeat_proto_goTypes = nil
	file_heartbeat_proto_depIdxs = nil
}
