syntax = "proto3";

package license.v1;

option go_package = "github.com/go-ragnaros/go-pulse/proto/licensepb";

service LicenseService {
  rpc RenewClientCert(RenewRequest) returns (RenewResponse);
  rpc Ping(PingRequest) returns (PingResponse);
}

message RenewRequest {
  string machine_fingerprint = 1;
  bytes  current_cert_pem    = 2;
}

message RenewResponse {
  bytes new_cert_pem      = 1;
  int64 server_time_unix  = 2;
}

message PingRequest {}

message PingResponse {
  int64 server_time_unix        = 1;
  int64 root_cert_expires_unix  = 2;
}
